services:
  - type: web
    name: servera-dashboard
    runtime: node
    rootDir: servera-dashboard
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: APP_URL
        value: https://servera-dashboard.netlify.app
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"
      - key: DISCORD_CLIENT_ID
        value: 1480878152816529501
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        value: https://servera-dashboard.netlify.app/auth/discord/callback
      - key: DISCORD_BOT_CLIENT_ID
        value: 1480878152816529501
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_BOT_PERMISSIONS
        value: "8"
      - key: ALLOW_DEV_LOGIN
        value: "false"
      - key: SEED_DEMO_DATA
        value: "false"
