create table if not exists public.guild_cache (
  guild_id text primary key,
  guild_name text not null,
  guild_icon text,
  bot_present boolean not null default false,
  channels_json jsonb not null default '[]'::jsonb,
  roles_json jsonb not null default '[]'::jsonb,
  stats_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.guild_settings (
  guild_id text primary key,
  ticket_category_id text,
  ticket_category_name text,
  support_roles_json jsonb not null default '[]'::jsonb,
  logs_enabled boolean not null default false,
  log_channel_id text,
  log_channel_name text,
  general_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.ticket_records (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  channel_id text not null,
  channel_name text,
  user_id text not null,
  username text not null,
  claimed_by_id text,
  claimed_by_name text,
  status text not null default 'open',
  topic text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.review_records (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  user_id text not null,
  username text not null,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.dashboard_sessions (
  id text primary key,
  csrf_token text not null,
  user_json jsonb not null,
  guilds_json jsonb not null default '[]'::jsonb,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.dashboard_oauth_states (
  id text primary key,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_ticket_records_guild_updated
  on public.ticket_records (guild_id, updated_at desc);

create index if not exists idx_review_records_guild_created
  on public.review_records (guild_id, created_at desc);

create index if not exists idx_dashboard_sessions_expires_at
  on public.dashboard_sessions (expires_at);

create index if not exists idx_dashboard_oauth_states_expires_at
  on public.dashboard_oauth_states (expires_at);
